### ISSUE TITLE
登場人物の定義(現時点でのとりあえず)

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/2023-quaint-api#2]
## なぜ
根幹となってくるクラスはこれらだろうと思われる
いったんそれらが持つフィールドを列挙して型付けすれば必要な関係性も見えてくるだろう
## やること
- [x] ユーザー・団体・公演・整理券のschema とmodelを作る

**Comment by Ekke-kuru2** [comment]
チケットも

**Comment by ekkekuru2** [comment]
Vote関係をついか
Like機能
後夜祭もこれを使うとなると、Programごとにタイトルとかを付けられた方がいいか

**Comment by ekkekuru2** [comment]
各nameとpasswordのvalidationの正規表現もうちょっとちゃんと検討する
