### ISSUE TITLE
タグを2つ以上追加可能にする

### ISSUE THREAD

**Issue by ItsukiKigoshi** [hibiya-itchief/2023-quaint-api#57]

**Comment by ekkekuru2** [comment]
テスト環境のデータベースのマイグレーションがうまくいっていなかったのが原因でした。
ソースコードは正しいので環境を作り直せば直ります！

**Comment by ekkekuru2** [comment]
今度はタグを重複して付けられるようになってしまった。今、GroupTagのテーブルはautoincrementなidをprimary_keyにしているが、group_idとtag_idの複合プライマリキーにした方がいいかも
